config/routes.rb
Booksiveread::Application.routes.draw do
  resources :books
  
  root :to => "books#index"
  

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :review, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def index
    @books = Book.all
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def create
    @book = Book.create!(params[:book])
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      redirect_to @book
    else
      render 'edit'
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def books_read_this_year
    @books = Book.all
    thisyear = 0
    d = Date.today
    @books.each do |b|      
      thisyear += 1 if b.created_at.between?(d.beginning_of_year, d+1.day)
    end
    thisyear
  end
  
  def books_per_week
    d = Date.today
    days = (d - d.beginning_of_year).to_i
    weeks = (days / 7).to_f
    (books_read_this_year / weeks).to_f.round(2)
  end  
end

app/views/books/edit.html.erb
<h3>Edit book</h3>

<%= form_for(@book) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div class="textarea">
    <%= f.label :review %>
    <%= f.text_area :review, :rows => 10, :class => "span8" %>
  </div>
  <div class="actions">
    <%= f.submit "Update", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/books/index.html.erb
<p class="lead">
  You have read <b><%= books_read_this_year %></b> books in <%= Date.today.year %>. That's a rate of <b><%= books_per_week %></b> per week.
</p>

<%= link_to "Add New Book", new_book_path, :class => "btn btn-primary" %>

<br><br>

<table class="table">
  <th>Number</th>
  <th>Title</th>
  <th>Author</th>
  <th>Created</th>
  
  <% @books.reverse.each_with_index do |book, counter| %>
    <tr>
      <td><%= counter + 1 %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.author %></td>
      <td><%= book.created_at.strftime("%d %B, %Y")%>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<h3>Add a new book to the database</h3>

<%= form_for(@book) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %><br />
  </div>
  <div class="textarea">
    <%= f.label :review %><br />
    <%= f.text_area :review, :rows => 10, :class => "span8" %>
  </div>
  <div class="actions">
    <%= f.submit "Create book", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="">
  <h3>Title</h3>
  <p><%= @book.title %></p>
</div>

<div class="">
  <h3>Author</h3>
  <p><%= @book.author %>
</div>

<div class="">
  <h3>Review</h3>
  <p><%= @book.review.gsub(/\n/, '<br />').html_safe %></p>
</div>

<br>

<div class="">
<%= link_to "Edit book details", edit_book_path(@book.id), :class => "btn btn-primary" %>
  
<%= link_to "Delete book", book_path(@book.id), :method => :delete, :confirm => "You sure?", :title => "Delete #{@book.title}", :class => "btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BookDatabase" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <!--<header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
        </div>
      </nav>
    </header>-->
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <div class="page-header">
                <h1><%= link_to "Books I've Read", '/' %></h1>
              </div>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>